package com.netradius.wirecard;

import com.netradius.wirecard.schema.*;
import com.netradius.wirecard.util.StringUtils;
import lombok.Data;
import lombok.experimental.Accessors;

import javax.xml.bind.JAXBElement;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.stream.Collectors;

/**
 * @author Erik R. Jensen
 */
@Data
@Accessors(chain = true)
public class WirecardSepaPayment {

	protected WirecardClient client;

	/**
	 * Identification number created by the merchant. Must be unique for each request.
	 * This is a required field.
	 */
	protected String requestId;

	/**
	 * The SEPA Direct Debit creditor ID used to identify the merchant.
	 * This is a required field.
	 */
	protected String creditorId;

	/**
	 * The amount in EUR.
	 * This is a required field.
	 */
	protected BigDecimal amount;

	/**
	 * Account holder's first name.
	 * This is a required field.
	 */
	protected String firstName;

	/**
	 * Account holder's last name.
	 * This is a required field.
	 */
	protected String lastName;

	/**
	 * Account holder's city.
	 * This field is optional.
	 */
	private String city;

	/**
	 * The account's holder state.
	 * This is optional.
	 */
	private String state;

	/**
	 * The account's holder address street1.
	 * This is optional.
	 */
	private String street1;

	/**
	 * The account's holder email street2.
	 * This is optional.
	 */
	private String street2;

	/**
	 * Account holder's country.
	 * This field is optional.
	 */
	private String country;

	/**
	 * Account holder's postal code.
	 * This field is optional.
	 */
	private String postalCode;

	/**
	 * The bank account number.
	 * This is a required field.
	 */
	protected String iban;

	/**
	 * The business identifier code of the bank.
	 * This is a required field.
	 */
	protected String bic;

	/**
	 * The ID of the signed mandate between the merchant and consumer generated by the merchant.
	 * This is a required field.
	 */
	protected String mandateId;

	/**
	 * The date the mandate was signed.
	 * This is a required field.
	 */
	protected Date signedDate;

	/**
	 * The date on which funds will be transferred.
	 * This is a optional field.
	 */
	protected Date dueDate;

	/**
	 * The transaction ID of the first transaction.
	 * This is a optional field.
	 */
	protected String  parentTransactionId;

	/**
	 * The description of the transaction.
	 * This is optional, maximum 100 characters allowed.
	 */
	protected String description;

	/**
	 * The account's holder email address.
	 * This is optional.
	 */
	private String email;

	/**
	 * The account's holder phone.
	 * This is optional.
	 */
	private String phone;

	/**
	 * The account's holder social security.
	 * This is optional.
	 */
	private String ssn;

	/**
	 * The account's holder email dateOfBirth.
	 * This is optional.
	 */
	private Date dateOfBirth;

	/**
	 * The notification email to receive the notifications.
	 * The url must be https.
	 *
	 * To receive the notification either notificationURL or notificationEmail must be not null.
	 */
	private String notificationEmail;

	/**
	 * The notification url to post the notifications.
	 * The url must be https.
	 *
	 * To receive the notification either notificationURL or notificationEmail must be not null.
	 */
	private String notificationURL;

	/**
	 * The transaction state for which notification to received.
	 * The value can be success or failure, can be null to receive to all notifications.
	 */
	private WirecardTransactionState notificationTransactionState;

	protected WirecardSepaPayment(WirecardClient client) {
		this.client = client;
	}

	public WirecardPaymentResponse submit() throws IOException {
		Payment payment = new Payment();

		MerchantAccountId merchantAccountId = new MerchantAccountId();
		merchantAccountId.setValue(client.merchantId);
		payment.setMerchantAccountId(merchantAccountId);

		AccountHolder accountHolder = new AccountHolder();
		accountHolder.setFirstName(firstName);
		accountHolder.setLastName(lastName);
		if (dateOfBirth != null) {
			accountHolder.setDateOfBirth(new SimpleDateFormat("yyyy-MM-dd").format(dateOfBirth));
		}
		accountHolder.setEmail(email);
		accountHolder.setPhone(phone);
		accountHolder.setSocialSecurityNumber(ssn);

		Address address = new Address();
		address.setCity(city);
		address.setCountry(country);
		address.setPostalCode(postalCode);
		address.setState(state);
		address.setStreet1(street1);
		address.setStreet2(street2);
		accountHolder.setAddress(address);
		payment.setAccountHolder(accountHolder);

		BankAccount bankAccount = new BankAccount();
		bankAccount.setBic(bic);
		bankAccount.setIban(iban);
		payment.setBankAccount(bankAccount);

		Mandate mandate = new Mandate();
		mandate.setMandateId(mandateId);
		mandate.setSignedDate(new SimpleDateFormat("yyyy-MM-dd").format(signedDate));
		payment.setMandate(mandate);

		Money money = new Money();
		money.setCurrency("EUR");
		money.setValue(amount);
		payment.setRequestedAmount(money);

		PaymentMethods paymentMethods = new PaymentMethods();
		PaymentMethod paymentMethod = new PaymentMethod();
		paymentMethod.setName(PaymentMethodName.SEPADIRECTDEBIT);
		paymentMethods.getPaymentMethod().add(paymentMethod);
		payment.setPaymentMethods(paymentMethods);

		payment.setTransactionType(TransactionType.PENDING_DEBIT);
		payment.setCreditorId(creditorId);
		payment.setRequestId(requestId);

		if (StringUtils.hasText(notificationEmail) || StringUtils.hasText(notificationURL)) {
			Notification notification = new Notification();
			if (notificationTransactionState != null) {
				notification.setTransactionState(TransactionState.fromValue(notificationTransactionState.value()));
			}
			notification.setUrl(notificationURL);
			if (StringUtils.hasText(notificationEmail)) {
				notification.setUrl("mailto:" + notificationEmail);
			}

			Notifications notifications = new Notifications();
			notifications.getNotification().add(notification);
			payment.setNotifications(notifications);
		}

		ObjectFactory objectFactory = new ObjectFactory();
		JAXBElement<Payment> jaxbElement = objectFactory.createPayment(payment);
		Payment result = client.httpClient.postEntity(client.url, Payment.class, jaxbElement);

		// TODO We will want to abstract this once we add support for other payment types
		WirecardPaymentResponse response = new WirecardPaymentResponse();
		response.setTransactionId(result.getTransactionId());
		response.setTransactionState(WirecardTransactionState.fromValue(result.getTransactionState().toString()));
		response.setCompletionDate(result.getCompletionTimeStamp().toGregorianCalendar().getTime());
		response.setProviderTransactionReferenceId(result.getProviderTransactionReferenceId());
//		response.setTransactionType(TransactionType.valueOf(result.getTransactionType()));//TODP
		response.setStatuses(result.getStatuses().getStatus().stream()
				.map(s -> (new WirecardPaymentStatus(s.getCode(), s.getDescription(), s.getSeverity().value())))
				.collect(Collectors.toCollection(ArrayList::new)));
		return response;
	}

}
